feat: Added a Togglable 0.5 Multiplier On The Speed of Driving And Turning
Dundee-Vi-Borgs/Vi-borgs-Robot-2023 pull request #19
Opened 2023-02-28 09:44 UTC by Spudman-llr

Added a togglable 0.5 multiplier on the speed of driving and turning and updated the README.md with the new controls.

2023-03-01 20:18 UTC, lovexar requested changes, later dismissed

2023-03-01 20:18 UTC, lovexar commented on README.md
> +	A (0): Drive/Turn Speed
Button should be changed from A to Right Bumper(5).

2023-03-04 02:07 UTC, Spudman-llr commented
Sorry I do not know what I am doing.

2023-03-06 20:16 UTC, lovexar approved these changes

2023-03-06 20:17 UTC, merged